# Generated by Django 5.2.4 on 2025-07-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_tarotcard_post_tarot_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotcard',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tarotcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tarot_cards/'),
        ),
        migrations.AlterField(
            model_name='tarotcard',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
